version: "2"
sql:
  - engine: "postgresql"
    queries: "query"
    schema: "schema/schema.sql"
    gen:
      go:
        package: "sqlc"
        out: "sqlc"
        sql_package: "pgx/v5"
        emit_interface: true
        emit_json_tags: true
        emit_pointers_for_null_types: true
        overrides:
        - db_type: "uuid"
          go_type:
            import: "github.com/google/uuid"
            type: "UUID"
